volumes:
  postgres_data:
  bundle_data:
  node_modules:

services:
  postgres:
    image: postgres:13.18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weathrify_development
      # Default superuser credentials
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
    environment:
      RAILS_ENV: development
    env_file:
      .env
    command: ["./bin/dev"]
    volumes:
      - .:/rails
      - bundle_data:/rails/vendor/bundle
      - node_modules:/rails/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
